### ISSUE TITLE
Jigsawpuzzle not working properly

### ISSUE THREAD

**Issue by rameshpolimeni** [worldsproject/android-jigsaw-puzzle-library#7]
I added this library into my puzzle same as it is. images are shown  but when i click image unfortunately mypuzzle has stopped error 

FATAL EXCEPTION: main
 E/AndroidRuntime(1706): java.lang.OutOfMemoryError
: E/AndroidRuntime(1706):   at android.graphics.Bitmap.nativeCreate(Native Method)
 E/AndroidRuntime(1706):    at android.graphics.Bitmap.createBitmap(Bitmap.java:697)
 E/AndroidRuntime(1706):    at android.graphics.Bitmap.createBitmap(Bitmap.java:674)
 E/AndroidRuntime(1706):    at android.graphics.Bitmap.createBitmap(Bitmap.java:641)
 E/AndroidRuntime(1706):    at org.worldsproject.puzzle.PuzzleGenerator.generatePuzzle(PuzzleGenerator.java:139)
 E/AndroidRuntime(1706):    at org.worldsproject.puzzle.PuzzleView.loadPuzzle(PuzzleView.java:45)
 E/AndroidRuntime(1706):    at org.worldsproject.puzzle.PuzzleSolveActivity.onStart(PuzzleSolveActivity.java:55)
 E/AndroidRuntime(1706):    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
 E/AndroidRuntime(1706):    at android.app.Activity.performStart(Activity.java:5143)
 E/AndroidRuntime(1706):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
 E/AndroidRuntime(1706):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
 E/AndroidRuntime(1706):    at android.app.ActivityThread.access$600(ActivityThread.java:141)
 E/AndroidRuntime(1706):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
 E/AndroidRuntime(1706):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(1706):     at android.os.Looper.loop(Looper.java:137)
 E/AndroidRuntime(1706):    at android.app.ActivityThread.main(ActivityThread.java:5103)
 E/AndroidRuntime(1706):    at java.lang.reflect.Method.invokeNative(Native Method)
 E/AndroidRuntime(1706):    at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime(1706):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 E/AndroidRuntime(1706):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 E/AndroidRuntime(1706):    at dalvik.system.NativeStart.main(Native Method)

please  help me ......thanks

**Comment by sibhe7** [comment]
have you run on real device? in my experience it (OutOfMemoryError) happen on emulator but work on real device

**Comment by rameshpolimeni** [comment]
Ya its working fine. i want to select camera and gallery images. camera
captured image  and gallery selected  image. how to add in this jigsaw
puzzle please help me

Thanks&regards
P Ramesh Babu
